//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insecap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public int id_alumno { get; set; }
        public string rut { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string genero { get; set; }
    }
}
